### ISSUE TITLE
_selfCloseTag not working

### ISSUE THREAD

**Issue by Desmodue** [davidcalhoun/jstoxml#53] opened 2021-10-12 13:58 UTC
Passing the {_selfCloseTag: false} option has no effect, tags are always self closed.

I think the issue may be in jstoxml.js line 326. The check is against the object looking for the _selfCloseTag attribute, not the config object.
I'd send a pull request but I don't understand the code well enough to be sure this doesn't break something else.

**Comment by davidcalhoun** [comment] 2021-10-12 14:43
Thanks for the heads up!  Can you provide some sample input that reproduces the issue?  There's a [test for this setting](https://github.com/davidcalhoun/jstoxml/blob/579f1d881fdf051fac9c6e69d51820e46a5f77a6/test.js#L986) that is passing.

**Comment by davidcalhoun** [comment] 2021-10-12 15:15
Thank you for the sample code, looks like the issue is the [docs](https://github.com/davidcalhoun/jstoxml#example-12-avoiding-self-closing-tags) are out of date, sorry about that!  I think that's how it worked in a previous version.

**Closed as completed** 2021-10-12 15:28 UTC
